[connections.postgresql]
dialect  = "postgresql"
host     = "TU_HOST"        # e.g. localhost
port     = "5432"
database = "TU_BASE_DATOS"  # e.g. Proyecto3
username = "TU_USUARIO"     # e.g. postgres
password = "TU_CONTRASEÑA"  # Tu contraseña de conexión de PgAdmin