[connections.postgresql]
dialect  = "postgresql"        # Indica el driver
host     = "localhost"         # O la IP de tu servidor
port     = "5432"              # Puerto por defecto
database = "plataforma_cursos" # Nombre de tu BD
username = "postgres"          # Usuario
password = "TuContraseña"      # Contraseña